name: News Update Service
on:
  schedule:
    - cron: '0 5 * * *'  # 05:00 UTC ist ca. 06:00/07:00 deutsche Zeit (Morgens)
    - cron: '0 11 * * *' # 11:00 UTC ist ca. 12:00/13:00 deutsche Zeit (Mittags)
    - cron: '0 17 * * *' # 17:00 UTC ist ca. 18:00/19:00 deutsche Zeit (Abends)
  workflow_dispatch:      # DAS ERLAUBT DAS MANUELLE STARTEN ÜBER GITHUB
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: pip install feedparser google-generativeai
      - name: Fetch News
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python fetch_news.py
      - name: Commit and push changes
        run: |
          git config --global user.name 'DailyBot'
          git config --global user.email 'bot@github.com'
          git add briefing.json
          git commit -m "Update News" || exit 0
          git push
